[platformio]
default_envs = xiaomiao

[env:xiaomiao]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.partitions = huge_app.csv
board_build.embed_files = data/cert/x509_crt_bundle.bin

lib_deps =
    bodmer/TFT_eSPI@2.5.43
    bblanchon/ArduinoJson@6.21.5

build_flags =
    -DUSER_SETUP_LOADED
    -include include/User_Setup.h
    -DCORE_DEBUG_LEVEL=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -mfix-esp32-psram-cache-strategy=memw

monitor_speed = 115200
monitor_filters = time, esp32_exception_decoder
